name: elo_ranking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  crypto: ^3.0.6
  postgres: ^3.5.5
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/money-svgrepo-com.svg
    - assets/icons/foosball.svg
